services:
  backend:
    build:
      context: "./3.Trabajos/2. Trabajo/backend"
      dockerfile: Dockerfile
    container_name: mm1k-backend
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: "./src/frontend"
      dockerfile: Dockerfile
    container_name: mm1k-frontend
    ports:
      - "5173:80"
    restart: unless-stopped
    depends_on:
      - backend
